package com.actornetwork.domain;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA Entity for website users
 * 
 * @author Wolfgang Zoppelt
 */

@Entity
@Table(name="USERS")
public class User {

	//User ID is auto generated by JPA
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;
	
	private String firstName;
	private String lastName;
	
	private String email;
	private String password;

	private boolean setUpComplete = false;
	private String about;

	/*
	 * AREA TO ADD MORE USER FIELDS
	 */
	
	//Lock out constructor so empty User isn't created
	private User() {}

    /**
	 * User constructor
	 * @param firstName
	 * @param lastName
	 * @param email
	 * @param password
	 * @author Wolfgang Zoppelt
	 */
	public User (String firstName, String lastName, String email, String password) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
	}


	/**
	 * @return User details in a string format
	 */
	@Override
	public String toString() {
		return "User{" +
				"id=" + id +
				", firstName='" + firstName + '\'' +
				", lastName='" + lastName + '\'' +
				", email='" + email + '\'' +
				", password='" + password + '\'' +
				", setUpComplete=" + setUpComplete +
				", about='" + about + '\'' +
				'}';
	}

	/**
	 * @return User's ID
	 */
	public Long getId() {
		return id;
	}
	
	/**
	 * @return User's first name
	 */
	public String getFirstName() {
		return firstName;
	}
	
	/**
	 * Sets user's first name
	 * @param firstName
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	/**
	 * @return User's last name
	 */
	public String getLastName() {
		return lastName;
	}
	
	/**
	 * Sets user's last name
	 * @param lastName
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * @return User's email address
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * Sets the user's email address
	 * @param email
	 */
	public void setEmail(String email) {
		this.email = email;
	}


    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAbout() {
        return about;
    }

    public void setAbout(String about) {
        this.about = about;
    }

    public boolean isSetUpComplete() {
        return setUpComplete;
    }

    public void setSetUpComplete(boolean setUpComplete) {
        this.setUpComplete = setUpComplete;
    }
}
